# Generated by Django 6.0 on 2025-12-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_nota_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='contenido',
            field=models.TextField(verbose_name='Contenido (HTML)'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
